### ISSUE TITLE
Vagrant has automatically selected the compatibility mode '2.0'

### ISSUE THREAD

**Issue by pnumboori** [oravirt/vagrant-vbox-rac#1]
==> racnode-dc1-1: Running provisioner: ansible_local...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.6.2).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

**Comment by oravirt** [comment]
Not sure what you mean? Do you have a problem with the compatibility?

**Comment by pnumboori** [comment]
Yes, provisioning is failing with error, my environment is 
Vagrant 2.1.2 and ansible 2.6.2.
I dont know how and where to set the compatibilty. Thanks for checking in on issues.

**Comment by oravirt** [comment]
Ok - then show me the actual error.
That’s not an error, it’s just information.

**Comment by pnumboori** [comment]
oot@praveen-HP-EliteBook-8460p:/media/praveen/Seagate Backup Plus Drive/18/vagrant-vbox-rac-master# vagrant provision
==> racnode-dc1-1: Running provisioner: ansible_local...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.6.2).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    racnode-dc1-1: Running ansible-playbook...
 [WARNING] Ansible is in a world writable directory (/vagrant), ignoring it as an ansible.cfg source.

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [racnode-dc1-2]
ok: [racnode-dc1-1]

TASK [init : Install packages] *************************************************
ok: [racnode-dc1-1] => (item=ntp)
ok: [racnode-dc1-2] => (item=ntp)
ok: [racnode-dc1-1] => (item=dnsmasq)
ok: [racnode-dc1-2] => (item=dnsmasq)

TASK [init : Make sure ntp is running] *****************************************
[DEPRECATION WARNING]: state=running is deprecated. Please use state=started. 
This feature will be removed in version 2.7. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: state=running is deprecated. Please use state=started. 
This feature will be removed in version 2.7. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

TASK [init : Generate /etc/hosts] **********************************************
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

TASK [init : Generate /etc/resolv.conf] ****************************************
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

TASK [init : Generate dnsmasq config] ******************************************
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

TASK [init : Start and enable dnsmasq] *****************************************
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

PLAY RECAP *********************************************************************
racnode-dc1-1              : ok=7    changed=0    unreachable=0    failed=0   
racnode-dc1-2              : ok=7    changed=0    unreachable=0    failed=0

**Comment by oravirt** [comment]
You need to set the environment variable setup to true (it’s in the documentation)
i.e
setup=true vagrant provision

**Comment by pnumboori** [comment]
Thanks, I missed that step, your documentation is pefect, my fault. 
Thanks again.its running now.

**Comment by oravirt** [comment]
Awesome! 
Happy to help
