### ISSUE TITLE
Can't build 11.2.0.4

### ISSUE THREAD

**Issue by programetica** [oravirt/vagrant-vbox-rac#2]
I've tried to build 11.2.0.4, with ol75 and ol69 without luck.  With ol75, I get this error:

.......................................
TASK [oraswgi-install : install-home-gi | Run oraInstroot script after installation] ***
changed: [racnode-dc1-2]
changed: [racnode-dc1-1]

TASK [oraswgi-install : install-home-gi | Run root script after installation (Master Node)] ***
fatal: [racnode-dc1-1]: FAILED! => {"changed": true, "cmd": "/u01/app/grid/product/11.2.0.4/grid/root.sh", "delta": "0:35:31.901595", "end": "2019-04-30 23:56:57.768903", "msg": "non-zero return code", "rc": 1, "start": "2019-04-30 23:21:25.867308", "stderr": "", "stderr_lines": [], "stdout": "Check /u01/app/grid/product/11.2.0.4/grid/install/root_racnode-dc1-1_2019-04-30_23-21-25.log for the output of root script", "stdout_lines": ["Check /u01/app/grid/product/11.2.0.4/grid/install/root_racnode-dc1-1_2019-04-30_23-21-25.log for the output of root script"]}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/vagrant/extra-provision/ansible-oracle/vbox-rac-dc1.retry

PLAY RECAP *********************************************************************
racnode-dc1-1              : ok=71   changed=42   unreachable=0    failed=1   
racnode-dc1-2              : ok=66   changed=38   unreachable=0    failed=0   
................................................................................

And in the root-racnode-dc1-1 log for ol75:
...................................................................................
Adding Clusterware entries to inittab
ohasd failed to start
Failed to start the Clusterware. Last 20 lines of the alert log follow:
2019-04-30 23:23:22.411:
[client(30726)]CRS-2101:The OLR was formatted using version 3.

/u01/app/grid/product/11.2.0.4/grid/perl/bin/perl -I/u01/app/grid/product/11.2.0.4/grid/perl/lib -I/u01/app/grid/product/11.2.0.4/grid/crs/install /u01/app/grid/product/11.2.0.4/grid/crs/install/rootcrs.pl execution failed
.............................................................................................................................

With ol69, I get this error on install (I think it may have to do with the version of Jinja being used in the vagrant box -- my solution may be to create a local version of the vagrant box and update the Jinja version and save it):
............................................................................................
TASK [oraasm-createdg : ASMCA | Create ASM diskgroups] *************************

TASK [oraasm-createdg : Print Results] *****************************************
fatal: [racnode-dc1-1]: FAILED! => {"msg": "template error while templating string: no filter named 'map'. String: {{ asmca.results|map(attribute='stdout_lines')|list }}"}
...ignoring

TASK [oraasm-createdg : ASMCA | List ASM diskgroups] ***************************

TASK [oraasm-createdg : list diskgroups] ***************************************
fatal: [racnode-dc1-1]: FAILED! => {"msg": "template error while templating string: no filter named 'map'. String: {{ srvctlasm.results|map(attribute='stdout_lines')|list }}"}
...ignoring

TASK [oraasm-manage-diskgroups : oraasm-manage-dgs | Manage diskgroups] ********
fatal: [racnode-dc1-1]: FAILED! => {"msg": "An unhandled exception occurred while templating '{% if item.attributes is defined %}{{item.attributes |default (omit) | map(attribute='name') | list }}{% else %}None{%endif%}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no filter named 'map'. String: {% if item.attributes is defined %}{{item.attributes |default (omit) | map(attribute='name') | list }}{% else %}None{%endif%}"}

...............................................................................................

And in the root-racnode-dc1-1 log for ol69:
..................................................................................................
ASM created and started successfully.

Disk Group crs created successfully.

clscfg: -install mode specified
Successfully accumulated necessary OCR keys.
Creating OCR keys for user 'root', privgrp 'root'..
Operation successful.
CRS-4256: Updating the profile
Successful addition of voting disk 0684b4435ed04f05bfa039a86c91af3c.
Successfully replaced voting disk group with +crs.
CRS-4256: Updating the profile
CRS-4266: Voting file(s) successfully replaced
'##  STATE    File Universal Id                File Name Disk group
--  -----    -----------------                --------- ---------
 1. ONLINE   0684b4435ed04f05bfa039a86c91af3c (ORCL:CRS01) [CRS]
Located 1 voting disk(s).
CRS-2672: Attempting to start 'ora.asm' on 'racnode-dc1-1'
CRS-2676: Start of 'ora.asm' on 'racnode-dc1-1' succeeded
CRS-2672: Attempting to start 'ora.CRS.dg' on 'racnode-dc1-1'
CRS-2676: Start of 'ora.CRS.dg' on 'racnode-dc1-1' succeeded
^[[1mConfigure Oracle Grid Infrastructure for a Cluster ... succeeded
^[[0m

..........................................................................

**Comment by oravirt** [comment]
Ok, I’ll have a look

**Comment by programetica** [comment]
I upgraded the rhel610 image to use python 3.4 because it has Jenja2, but didn't know Ansible requires a minimum of python 3.5 if you're using python 3.  For some reason python 3.6.3 is being a pain to install.
……………………………………………………………………………………………………………………………………………………

==> racnode-dc1-1: Running provisioner: ansible_local...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.6.16).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

  racnode-dc1-1: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [racnode-dc1-1]: FAILED! => {"changed": false, "msg": "Ansible requires a minimum of Python2 version 2.6 or Python3 version 3.5. Current version: 3.4.10 (default, Apr  8 2019, 02:18:20) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]"}
fatal: [racnode-dc1-2]: FAILED! => {"changed": false, "msg": "Ansible requires a minimum of Python2 version 2.6 or Python3 version 3.5. Current version: 3.4.10 (default, Apr  8 2019, 02:18:20) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]"}
	to retry, use: --limit @/vagrant/base-provision/init.retry

PLAY RECAP *********************************************************************
racnode-dc1-1              : ok=0    changed=0    unreachable=0    failed=1   
racnode-dc1-2              : ok=0    changed=0    unreachable=0    failed=1

**Comment by programetica** [comment]
I upgraded to python3.5 on the RHEL610 box and added the CENTOS 6.10 repository for the necessary dependencies and saved this version as a local vagrant box.  After including it in the host.yml file and running it for 11.2.0.4, I got the following error:

..................................................................................................................................................................

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [racnode-dc1-1]
ok: [racnode-dc1-2]

TASK [init : Install packages] *************************************************

failed: [racnode-dc1-2] (item=ntp) => {"changed": false, "item": "ntp", "module_stderr": "Shared connection to 192.168.7.11 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_smf9xb4p/ansible_module_yum.py\", line 285, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"<frozen importlib._bootstrap>\", line 968, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 957, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 634, in _load_backward_compatible\r\n  File \"/tmp/ansible_smf9xb4p/ansible_modlib.zip/ansible/module_utils/urls.py\", line 345, in <module>\r\nAttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'\r\n", "msg": "MODULE FAILURE", "rc": 1}

failed: [racnode-dc1-1] (item=ntp) => {"changed": false, "item": "ntp", "module_stderr": "Shared connection to 192.168.7.10 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_27fko96v/ansible_module_yum.py\", line 285, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"<frozen importlib._bootstrap>\", line 968, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 957, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 634, in _load_backward_compatible\r\n  File \"/tmp/ansible_27fko96v/ansible_modlib.zip/ansible/module_utils/urls.py\", line 345, in <module>\r\nAttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'\r\n", "msg": "MODULE FAILURE", "rc": 1}

failed: [racnode-dc1-2] (item=dnsmasq) => {"changed": false, "item": "dnsmasq", "module_stderr": "Shared connection to 192.168.7.11 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_c2kz_pvw/ansible_module_yum.py\", line 285, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"<frozen importlib._bootstrap>\", line 968, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 957, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 634, in _load_backward_compatible\r\n  File \"/tmp/ansible_c2kz_pvw/ansible_modlib.zip/ansible/module_utils/urls.py\", line 345, in <module>\r\nAttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'\r\n", "msg": "MODULE FAILURE", "rc": 1}

failed: [racnode-dc1-1] (item=dnsmasq) => {"changed": false, "item": "dnsmasq", "module_stderr": "Shared connection to 192.168.7.10 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible__ab6di8a/ansible_module_yum.py\", line 285, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"<frozen importlib._bootstrap>\", line 968, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 957, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 634, in _load_backward_compatible\r\n  File \"/tmp/ansible__ab6di8a/ansible_modlib.zip/ansible/module_utils/urls.py\", line 345, in <module>\r\nAttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'\r\n", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/vagrant/base-provision/init.retry

PLAY RECAP *********************************************************************
racnode-dc1-1              : ok=1    changed=0    unreachable=0    failed=1   
racnode-dc1-2              : ok=1    changed=0    unreachable=0    failed=1 

..................................................................................................................................................

I did some research and it doesn't look like there are any easy fixes that I could see for this.  All of the links were either very vague or very involved.

**Comment by programetica** [comment]
Some of this is explained here:  https://community.oracle.com/thread/3976294 

***************************
    Adding Clusterware entries to inittab

RHEL 7 is using upstart, not inittab anymore. I am pretty sure that the installer should recognize that automatically. For some reason it does not recognize it in your case. So the OHASD is being added to inittab, but this will never ever lead to an automated start of OHASD. In the first place, you can try to start OHASD manually and then create your own upstart configuration. Nevertheless you should try to find the reason why the installer is not using upstart.
****************************

****************************
Below output indicates that you have opted to run the "root" related scripts automatically as a part of installation of GI.

 
Adding Clusterware entries to inittab

ohasd failed to start

Failed to start the Clusterware. Last 20 lines of the alert log follow:

2016-09-28 08:53:42.739:

[client(5107)]CRS-2101:The OLR was formatted using version 3.

The installer attempted to run the "root.sh" and failed to start the OHAS daemon. As the installer is not able to progress due to failure of root.sh script.

The previous release of Oracle Linux / RHEL uses initd for running the processes and restarting them.

Where as Oracle Linux / RHEL7 expects to use systemd rather than initd, and root.sh script doesn’t handle this change behavior currently

This issue has been investigated in the below bug:

Bug 18370031  - RC SCRIPTS (/ETC/RC.D/RC.* , /ETC/INIT.D/* ) ON OL7 FOR CLUSTERWARE

Refer below MOS document for the resolution:

Install of Clusterware fails while running root.sh on OL7 - ohasd fails to start (Doc ID 1959008.1)

You need kill the OUI screen, apply patch for bug 18370031, or apply latest GI PSU and then proceed with rerunning the root.sh script.

After execution of root.sh script, refer below MOS document to complete the post root.sh activities.

How to Complete Grid Infrastructure Configuration Assistant(Plug-in) if OUI is not Available (Doc ID 1360798.1)

If you are still not able to proceed, consider creating SR with Oracle Support.
****************************

Please check Installation walk-through - Oracle Grid/RAC 11.2.0.4 on Oracle Linux 7 (Doc ID 1951613.1)
